version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_chatbot
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - mongo  # Add MongoDB dependency
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MONGO_URI=mongodb://mongo:27017  # Optional: if your app reads this
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    command: serve

volumes:
  ollama_models:
  mongo_data:
